replicas: 2

labels:
  apps1: ims
  apps2: mongo 

image:
  name1: bharathsunny3006/ps
  name2: mongo
  tag1: latest
  tag2: latest

source:
  port1: 3000
  port2: 27017

service:
  type: LoadBalancer

env:
  name: MONGO_URI
  link: "mongodb://{{ .Release.Name }}-mongoservice:27017/job_portal"
