
       apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-imsdeployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.labels.apps1 }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.apps1 }}
    spec:
      containers:
      - name: ims
        image: {{ .Values.image.name1 }}:{{ .Values.image.tag1 }}
        ports:
        - containerPort: {{ .Values.source.port1 }}
      env:
      - name: {{ .Values.env.name }}
        value: "mongodb://{{ .Release.Name }}-mongoservice:27017/job_portal"

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-imservice
spec:
  selector:
    app: {{ .Values.labels.apps1 }}
  ports:
  - port: {{ .Values.source.port1 }}
    targetPort: {{ .Values.source.port1 }}
  type: {{ .Values.service.type }}
            






